/** Ported from iOS LeagueFilterConfig.upperDivisions (case-insensitive match). */
export const STATSTRIKE_UPPER_DIVISIONS: readonly string[] = [
  "England: Premier League",
  "England: Championship",
  "Spain: La Liga",
  "Spain: LaLiga",
  "Spain: Primera Division",
  "Spain: La Liga 2",
  "Spain: LaLiga2",
  "Spain: Segunda Division",
  "Italy: Serie A",
  "Italy: Serie B",
  "Germany: Bundesliga",
  "Germany: Bundesliga 1",
  "Germany: 2. Bundesliga",
  "Germany: Bundesliga 2",
  "France: Ligue 1",
  "France: Ligue 2",
  "Netherlands: Eredivisie",
  "The Netherlands: Eredivisie",
  "Netherlands: Eerste Divisie",
  "Portugal: Primeira Liga",
  "Portugal: Liga de Honra",
  "Portugal: Segunda Liga",
  "Scotland: Scottish Premiership",
  "Scotland: Premiership",
  "Scotland: Championship",
  "Belgium: Pro League",
  "Belgium: Jupiler Pro League",
  "Belgium: Challenger Pro League",
  "Turkey: Super Lig",
  "Turkey: S\u00fcper Lig",
  "Turkey: 1. Lig",
  "Turkey: 2. Lig",
  "Austria: Bundesliga",
  "Austria: 2. Liga",
  "Switzerland: Super League",
  "Switzerland: Challenge League",
  "Greece: Super League",
  "Greece: Super League 2",
  "Poland: Ekstraklasa",
  "Poland: I Liga",
  "Czech-Republic: Czech Liga",
  "Czech Republic: Czech Liga",
  "Czech-Republic: FNL",
  "Czech Republic: FNL",
  "Czech-Republic: Fortuna Liga",
  "Slovakia: Fortuna Liga",
  "Slovakia: 1. liga",
  "Slovakia: 2. liga",
  "Slovenia: 1. SNL",
  "Slovenia: 2. SNL",
  "Hungary: NB I",
  "Hungary: NB II",
  "Romania: Liga 1",
  "Romania: Liga 2",
  "Bulgaria: First League",
  "Bulgaria: Second League",
  "Croatia: HNL",
  "Croatia: First Football League",
  "Serbia: Super Liga",
  "Ukraine: Premier League",
  "Ukraine: First League",
  "Denmark: Superliga",
  "Denmark: 1st Division",
  "Sweden: Allsvenskan",
  "Sweden: Superettan",
  "Norway: Eliteserien",
  "Norway: Norway First Division",
  "Iceland: Besta",
  "Iceland: Premier",
  "Finland: Veikkausliiga",
  "Finland: Ykkonen",
  "Luxembourg: National Division",
  "Wales: Cymru Premier",
  "Wales: FAW Championship",
  "Wales: Premier League",
  "Andorra: 1a Divisi\u00f3",
  "Andorra: Primera Divisi\u00f3",
  "San-Marino: Campionato",
  "UEFA: Champions League",
  "UEFA: Europa League",
  "UEFA: Europa Conference League",
  "World: Champions League",
  "World: Europa League",
  "World: Europa Conference League",
  "World: UEFA Champions League",
  "World: UEFA Europa League",
  "World: UEFA Europa Conference League",
  "Europe: Champions League",
  "Europe: Europa League",
  "Europe: Europa Conference League",
  "USA: Major League Soccer",
  "USA: MLS",
  "USA: USL Championship",
  "Mexico: Liga MX",
  "Mexico: Liga de Expansion",
  "Argentina: Primera Division",
  "Argentina: Liga Profesional Argentina",
  "Argentina: Primera Nacional",
  "Brazil: Serie A",
  "Brazil: Serie B",
  "Brazil: Brasileiro Serie A",
  "Brazil: Brasileiro Serie B",
  "Colombia: Primera A",
  "Colombia: Categoria Primera A",
  "Chile: Primera Division",
  "Chile: Primera B",
  "Peru: Liga 1",
  "Ecuador: Serie A",
  "Uruguay: Primera Division",
  "Paraguay: Primera Division",
  "Bolivia: Primera Division",
  "Venezuela: Primera Division",
  "Costa Rica: Primera Division",
  "Honduras: Liga Nacional",
  "El-Salvador: Primera Division",
  "El Salvador: Primera Division",
  "Nicaragua: Primera Division",
  "Panama: Liga Paname\u00f1a",
  "Jamaica: Premier League",
  "Trinidad-And-Tobago: Pro League",
  "Canada: Canadian Premier League",
  "Japan: J. League Div.1",
  "Japan: J. League Div. 1",
  "Japan: J1 League",
  "Japan: J2 League",
  "Japan: J. League Div.2",
  "Japan: J. League Div. 2",
  "China: Super League",
  "China: China League One",
  "South-Korea: K League 1",
  "South-Korea: K League 2",
  "Australia: A-League",
  "Australia: A-League Men",
  "Australia: NPL",
  "India: Indian Super League",
  "India: I-League",
  "Malaysia: Super League",
  "Malaysia: Premier League",
  "Thailand: Thai League 1",
  "Thailand: Thai League 2",
  "Vietnam: V.League 1",
  "Indonesia: Liga 1",
  "Singapore: Premier League",
  "Hong-Kong: Premier League",
  "Hong Kong: Premier League",
  "Chinese-Taipei: Taiwan Football Premier League",
  "Chinese Taipei: Taiwan Football Premier League",
  "Saudi-Arabia: Pro League",
  "UAE: Pro League",
  "Qatar: Stars League",
  "Iran: Persian Gulf Pro League",
  "Iraq: Iraqi Premier League",
  "South-Africa: Premier League",
  "South Africa: Premier League",
  "South-Africa: Premier Division",
  "South-Africa: 1st Division",
  "Egypt: Premier League",
  "Morocco: Botola",
  "Nigeria: NPFL",
  "Tunisia: Ligue 1",
  "Algeria: Ligue 1",
  "Ghana: Premier League",
  "Cameroon: Elite One",
  "Kenya: Premier League",
  "Zimbabwe: Premier Soccer League",
  "New-Zealand: National League",
  "New Zealand: National League",
  "Fiji: Premier League",
  "Papua-New-Guinea: National Soccer League",
];

const upperSet = new Set(STATSTRIKE_UPPER_DIVISIONS.map((s) => s.toLowerCase()));

export function isUpperDivision(country: string, name: string): boolean {
  const key = `${country.trim()}: ${name.trim()}`.toLowerCase();
  return upperSet.has(key);
}
