import { App } from '@/types/app';

// ADD YOUR APP DATA HERE!
export const apps: App[] = [
  {
    id: 'stat-strike',
    name: 'StatStrike',
    tagline: 'Smart Football Predictions',
    description: 'A subscription-based sports prediction app featuring Firebase integration, premium SwiftUI animations, and a proprietary statistical algorithm — built with a focus on delightful UX and transparent performance tracking.',
    color: '#10B981',
    icon: '/images/stat-strike-icon.png',
    screenshots: [
      '/images/stat-strike-1.png',
      '/images/stat-strike-2.png',
      '/images/stat-strike-3.png',
      '/images/stat-strike-4.png',
    ],
    features: [
      'MVVM architecture with Swift Concurrency (async/await)',
      'Firebase Realtime Database integration',
      'Premium UI: animated gradients, skeleton loaders, haptics, confetti',
      'Dark Mode with semantic colors throughout',
      'Visual confidence gauges & live match pulsing indicators',
      'Subscription management with free trial support',
      'Local caching for offline access',
      'Transparent Track Record with win/loss reconciliation',
    ],
    platform: 'iOS',
    status: 'live',
    googlePlayStatus: 'in-review',
    appStoreUrl: 'https://apps.apple.com/gb/app/statstrike/id6757434374',
    appStoreTrialNote: 'First week free!',
    blueskyUrl: 'https://bsky.app/profile/statstrikeapp.bsky.social',
    blueskyLabel: '@statstrikeapp',
    contentRatingUrl: '/statstrike/content-rating',
    privacyUrl: '/privacy/statstrike',
    termsUrl: '/terms/statstrike',
    supportUrl: '/support/statstrike',
  },
  {
    id: 'goallab',
    name: 'GoalLab',
    tagline: 'Over / Under 2.5 forecast lab',
    description:
      'A football prediction app for Over and Under 2.5 Goals markets, built around an 11-criteria algorithm with forecaster confidence, full track history, and a transparent track record. GoalLab surfaces curated Best Picks and performance insights, with an introductory subscription trial, ad-supported access during trial, and monthly or lifetime paid access options.',
    color: '#0891B2',
    icon: '/images/goallab-icon.png',
    screenshots: [
      '/images/goallab-1.png',
      '/images/goallab-2.png',
      '/images/goallab-3.png',
    ],
    features: [
      '11-criteria algorithm for Over & Under 2.5 goal bands',
      'Forecaster confidence, full track history, transparent track record',
      'Curated Best Picks when strict quality thresholds are met',
      'Firebase cloud-synced track record across devices',
      'Best Performing Leagues & Top Criteria insights',
      'Introductory trial with ads, then monthly or lifetime paid access',
    ],
    platform: 'iOS',
    status: 'live',
    googlePlayStatus: 'in-review',
    appStoreUrl: 'https://apps.apple.com/gb/app/goallab/id6759168029',
    appStoreTrialNote: '3-day intro trial · monthly or lifetime access',
    contentRatingUrl: '/goallab/content-rating',
    privacyUrl: '/privacy/goallab',
    termsUrl: '/terms/goallab',
  },
  {
    id: 'popgoals',
    name: 'PopGoals',
    tagline: 'Bubble lake, live hot-zone targets',
    description:
      'PopGoals brings the day’s football targets into a calm “bubble lake”: fixtures move through qualified, watching, trigger, and settled states, with a focus on hot scoring zones for in-play use. Firebase-backed targets, readable match cards, exact landed goal times on settled wins, and motion-aware visuals you can pause.',
    color: '#9333EA',
    icon: '/images/popgoals-icon.png',
    screenshots: [],
    features: [
      'Bubble lake UI with qualified, watching, trigger, win, and loss mothers',
      'Hot-zone-first match cards with target minute windows and landed goal times',
      'Firebase-backed daily targets with local caching and alert support',
      'Support, privacy, terms, disclaimer, and content-rating pages on the GoalLab site',
      'SwiftUI visuals with curated chroma phases and accessibility-friendly motion controls',
    ],
    platform: 'iOS',
    status: 'live',
    appStoreUrl: 'https://apps.apple.com/gb/app/popgoals/id6762088212',
    appStoreTrialNote: 'First 7 days free',
    websiteUrl: '/support/popgoals',
    privacyUrl: '/privacy/popgoals',
    termsUrl: '/terms/popgoals',
    supportUrl: '/support/popgoals',
    disclaimerUrl: '/disclaimer/popgoals',
    contentRatingUrl: '/popgoals/content-rating',
  },
  {
    id: 'maincode',
    name: 'MainCode',
    tagline: 'Your postcode. Your events.',
    description:
      'Discover live music and theatre near you. Search by postcode, browse events and venues, save favourites, and plan your week. Open any listing for details, share with friends, or add it to the in-app calendar.',
    color: '#E07359',
    icon: '/images/maincode-icon.png',
    screenshots: [
      '/images/maincode-1.png',
      '/images/maincode-2.png',
      '/images/maincode-3.png',
      '/images/maincode-4.png',
    ],
    features: [
      'Postcode-based event discovery (PredictHQ)',
      'Events and Venues tabs with search and date filters',
      'Save events and batch-share via Messages or Messenger',
      'In-app calendar planner with "Add to calendar" from events',
      'Optional Firebase backup for offline/fallback data',
      'SwiftUI, Firebase Auth & Realtime Database',
    ],
    platform: 'iOS',
    status: 'live',
    appStoreUrl: 'https://apps.apple.com/gb/app/maincode/id6758269900',
    privacyUrl: '/privacy/maincode',
    supportUrl: '/support/maincode',
  },
  {
    id: 'contact-care',
    name: 'Contact Care',
    tagline: 'Stay in touch with the people who matter',
    description:
      'Contact Care helps you maintain real relationships with gentle reminders for the people who matter. Configure weekly, monthly, spaced, and special schedules per contact, see who’s due today as floating reminder bubbles, personalise themes and languages, and unlock Premium to remove ads — built with Flutter for iOS and Android.',
    color: '#14B8A6',
    icon: '/images/contact-care-icon.png',
    screenshots: [
      '/images/contact-care-1.png',
      '/images/contact-care-2.png',
      '/images/contact-care-3.png',
    ],
    features: [
      'Pending reminder dashboard with contact bubbles',
      'Per-contact weekly, monthly, spaced, and special schedules',
      'Device notifications when it’s time to reach out',
      'Theme colour and language personalisation',
      'Premium removes all advertisements',
      'Cross-platform Flutter app for iOS and Android',
    ],
    platform: 'Cross-platform',
    status: 'beta',
    privacyUrl: '/privacy/contact-care',
    supportUrl: '/support/contact-care',
    termsUrl: '/terms/contact-care',
  },
  {
    id: 'draw-with-friends',
    name: 'Draw With Friends',
    tagline: 'Real-time collaborative drawing',
    description: 'A fun, interactive iOS app where friends can draw together in real-time. Features include turn-based and simultaneous drawing modes, echo effects, and photo backgrounds.',
    color: '#FF6B9D',
    icon: '/images/draw-with-friends-icon.png',
    screenshots: [
      '/images/draw-with-friends-1.png',
      '/images/draw-with-friends-2.png',
      '/images/draw-with-friends-3.png',
    ],
    features: [
      'Real-time collaboration',
      'Turn-based & simultaneous modes',
      'Echo drawing effects',
      'Photo backgrounds',
      'Room-based sessions',
    ],
    appStoreUrl: 'https://apps.apple.com/gb/app/draw-with-friends/id6755112480',
    platform: 'iOS',
    status: 'live',
  },
  {
    id: 'doomscroll-stopper',
    name: 'Doomscroll Stopper',
    tagline: 'Break the scroll, reclaim your time',
    description: 'Stop endless scrolling with intelligent app blocking and mindful usage reminders. Take back control of your digital habits.',
    // Warm orange that matches the app's highlight colour better than pink
    color: '#F97316',
    icon: '/images/doomscroll-stopper-icon.png',
    screenshots: [
      '/images/doomscroll-stopper-1.png',
      '/images/doomscroll-stopper-2.png',
    ],
    features: [
      'Smart scroll detection',
      'Usage time limits',
      'Break reminders',
      'App blocking',
      'Daily insights',
    ],
    appStoreUrl: 'https://apps.apple.com/gb/app/doomscroll-stopper/id6754539688',
    platform: 'iOS',
    status: 'live',
  },
  {
    id: 'nudgetronic',
    name: 'Nudgetronic',
    tagline: 'Screen time management done right',
    description: 'Take control of your digital wellbeing with smart app blocking, grace periods, and auto-end timers.',
    color: '#4A90E2',
    icon: '/images/nudgetronic-icon.png',
    screenshots: [
      '/images/nudgetronic-1.png',
      '/images/nudgetronic-2.png',
      '/images/nudgetronic-3.png',
    ],
    features: [
      'Full-screen shields',
      '2-minute grace periods',
      'Auto-end timers',
      'Web domain blocking',
      'Category-based limits',
    ],
    appStoreUrl: 'https://apps.apple.com/gb/app/nudgetronic/id6752445547',
    platform: 'iOS',
    status: 'live',
    privacyUrl: '/privacy/nudgetronic',
    supportUrl: '/support/nudgetronic',
  },
  {
    id: 'desktop-totem',
    name: 'Desktop Totem',
    tagline: 'Your most-used apps, stacked and ready',
    description:
      'Desktop Totem keeps your most-used Mac apps in a live "totem" on your screen so you can jump back into your real work with a single click.',
    color: '#1E293B',
    icon: '/images/desktop-totem-icon.png',
    screenshots: ['/images/desktop-totem-1.png', '/images/desktop-totem-2.png'],
    features: [
      'Live ranking of your most-used apps',
      'Slim menu bar popover and optional desktop totem',
      'Always-on-top mode with one-click "hide others"',
      'Per-app quick notes ("what was I working on?")',
      'VoiceOver-friendly navigation with clear labels',
    ],
    platform: 'macOS',
    status: 'live',
    appStoreUrl: 'https://apps.apple.com/gb/app/desktop-totem/id6755545138?mt=12',
    supportUrl: '/support/desktop-totem',
    privacyUrl: '/privacy/desktop-totem',
    accessibilityUrl: '/accessibility/desktop-totem',
  },
  {
    id: 'icon-resizer-apple-apps',
    name: 'AssetForge',
    tagline: 'Developer Image Toolkit — icons, screenshots & store assets',
    description:
      'A native macOS developer toolkit: drag in a master image (or prepare it in Image Lab), then generate Xcode-ready Apple icon packs (including watchOS, visionOS, and tvOS), Google Play launcher and Adaptive Icons, store screenshots, Web & Social cards, Brand Assets, and YouTube channel sizes. Exports respect sandboxed folder access on the Mac App Store build.',
    color: '#8B5CF6',
    icon: '/images/icon-resizer-apple-apps-icon.png',
    screenshots: [],
    features: [
      'Apple AppIcon.appiconset packs for iOS, macOS, watchOS, visionOS, and tvOS',
      'Google Play mipmaps, Adaptive Icons, 512 listing icon, and feature graphic',
      'App Store and Play Console screenshot pipelines with clear device-class labels',
      'Web & Social, Brand Assets, and YouTube Channel export presets',
      'Image Lab: crop, pad, compose, then hand off into any pipeline',
      'SwiftUI interface with drag-and-drop and sandboxed folder pickers',
    ],
    platform: 'macOS',
    status: 'beta',
    websiteUrl: 'https://github.com/JamieNudge/IconResizerAppleApps',
    privacyUrl: '/privacy/assetforge',
    supportUrl: '/support/assetforge',
    termsUrl: '/terms/assetforge',
    accessibilityUrl: '/accessibility/assetforge',
  },
  {
    id: 'aikido-vocabulary-app',
    name: 'Aikido Vocabulary App',
    tagline: 'Japanese Language Trainer for students of Aikido',
    description:
      'A focused Japanese vocabulary trainer for Aikido students. Learn key dojo phrases, technique names and etiquette terms with simple drills you can run between classes.',
    // Use a calm indigo/blue that matches the iOS-style screenshots better than brown
    color: '#2563EB',
    icon: '/images/aikido-vocabulary-icon.png',
    screenshots: [
      // First screenshot is used for the card; use the new main shot there
      '/images/aikido-vocab-main.png',
      '/images/aikido-vocab-1.png',
      '/images/aikido-vocab-2.png',
      '/images/aikido-vocab-3.png',
      '/images/aikido-vocab-4.png',
    ],
    features: [
      'Curated Aikido dojo vocabulary',
      'Reading + English meaning for each term',
      'Lightweight on-device progress tracking',
      'No accounts and no ads',
      'Designed for quick review between classes',
    ],
    platform: 'iOS',
    status: 'beta',
    privacyUrl: '/privacy/aikido-vocabulary',
    contentRatingUrl: '/aikido-vocabulary/content-rating',
  },
  {
    id: 'recipe-saviour',
    name: 'Recipe Saviour',
    tagline: 'Save recipes from any website',
    description: 'Extract and save recipes from any website with a single tap. Recipe Saviour automatically parses ingredients, instructions, and cooking times into a clean, readable format. Plan your weekly meals and generate smart shopping lists.',
    color: '#EF4444',
    icon: '/images/recipe-saviour-icon.png',
    screenshots: [
      '/images/recipe-saviour-2025-12-19-1.png',
      '/images/recipe-saviour-2025-12-19-2.png',
      '/images/recipe-saviour-2025-12-19-3.png',
    ],
    features: [
      'Extract recipes from any website',
      'Clean, readable format',
      'Save ingredients and instructions',
      'Smart meal planner with shared ingredients',
      'Auto-generated shopping lists',
      'Offline access to saved recipes',
    ],
    platform: 'iOS',
    status: 'live',
    appStoreUrl: 'https://apps.apple.com/gb/app/recipe-saviour/id6755662996',
    supportUrl: '/support/recipe-saviour',
    privacyUrl: '/privacy/recipe-saviour',
    disclaimerUrl: '/disclaimer/recipe-saviour',
  },
  {
    id: 'ball-finder',
    name: 'Ball Finder',
    tagline: 'Find your lost balls...',
    description: 'Use your iPhone camera to scan and find lost balls in the park. Ball Finder uses real-time detection with ML training to help you locate balls quickly, with visual guidance and haptic feedback.',
    color: '#FBBF24',
    icon: '/images/ball-finder-icon.png',
    screenshots: [
      '/images/ball-finder-1.png',
      '/images/ball-finder-2.png',
      '/images/ball-finder-3.png',
    ],
    features: [
      'Real-time camera scanning',
      'ML-powered ball detection',
      'Cumulative learning from training photos',
      'Visual bounding boxes and distance hints',
      'Haptic feedback when balls detected',
      'Diagnostic logging for troubleshooting',
    ],
    platform: 'iOS',
    status: 'beta',
  },
  {
    id: 'roma',
    name: 'Roma',
    tagline: 'All thoughts lead to Rome...',
    description: 'A delightful daily reminder app based on the premise that all men think about Rome every day. Set your reminder time, answer the daily question, and discover fun facts about Ancient Rome.',
    color: '#DC2626',
    icon: '/images/roma-icon.png',
    screenshots: [
      '/images/roma-1.png',
      '/images/roma-2.png',
      '/images/roma-3.png',
      '/images/roma-4.png',
    ],
    features: [
      'Daily reminder notifications',
      'Roman numeral time picker',
      'Visual countdown timer',
      'Fun facts about Ancient Rome',
      'Beautiful Palatino typography',
      'Thoughtful UX with 3-second delays',
    ],
    platform: 'iOS',
    status: 'beta',
  },
  {
    id: 'research-lab',
    name: 'Research Lab',
    tagline: 'Data-driven pattern recognition',
    description: 'A macOS research tool that analyzes large datasets using multi-criteria statistical models to identify high-confidence patterns. Features real-time API integration, intelligent caching for offline analysis, and exportable results for performance tracking.',
    color: '#10B981',
    icon: '/images/research-lab-icon.png',
    screenshots: [
      // No screenshots - private research tool
    ],
    features: [
      'Multi-criteria statistical analysis engine',
      'API integration with manual control',
      'Smart data caching and offline analysis',
      'Confidence scoring and filtering',
      'Searchable dataset with 1000+ daily entries',
      'Export capabilities for performance tracking',
    ],
    platform: 'macOS',
    status: 'beta',
  },
];

