import { App } from '@/types/app';

// ADD YOUR APP DATA HERE!
export const apps: App[] = [
  {
    id: 'stat-strike',
    name: 'StatStrike',
    tagline: 'Smart Football Predictions',
    description: 'A subscription-based sports prediction app featuring Firebase integration, premium SwiftUI animations, and a proprietary statistical algorithm — built with a focus on delightful UX and transparent performance tracking.',
    color: '#10B981',
    icon: '/images/stat-strike-icon.png',
    screenshots: [
      '/images/stat-strike-1.png',
      '/images/stat-strike-2.png',
      '/images/stat-strike-3.png',
      '/images/stat-strike-4.png',
    ],
    features: [
      'MVVM architecture with Swift Concurrency (async/await)',
      'Firebase Realtime Database integration',
      'Premium UI: animated gradients, skeleton loaders, haptics, confetti',
      'Dark Mode with semantic colors throughout',
      'Visual confidence gauges & live match pulsing indicators',
      'Subscription management with free trial support',
      'Local caching for offline access',
      'Transparent Track Record with win/loss reconciliation',
    ],
    platform: 'iOS',
    status: 'live',
    googlePlayStatus: 'in-review',
    appStoreUrl: 'https://apps.apple.com/gb/app/statstrike/id6757434374',
    appStoreTrialNote: 'First week free!',
    blueskyUrl: 'https://bsky.app/profile/statstrikeapp.bsky.social',
    blueskyLabel: '@statstrikeapp',
    contentRatingUrl: '/statstrike/content-rating',
    privacyUrl: '/privacy/statstrike',
    termsUrl: '/terms/statstrike',
    supportUrl: '/support/statstrike',
  },
  {
    id: 'goallab',
    name: 'GoalLab',
    tagline: 'AI-Powered Football Forecast Lab',
    description: 'A multi-model football prediction app that analyses Over and Under 2.5 Goals markets using four independent statistical models. GoalLab curates high-confidence Best Picks based on model agreement and historical win rates, with transparent confidence bands, a cloud-synced track record, and an ad-supported free tier.',
    color: '#0891B2',
    icon: '/images/goallab-icon.png',
    screenshots: [
      '/images/goallab-1.png',
      '/images/goallab-2.png',
      '/images/goallab-3.png',
    ],
    features: [
      'Multi-model Over & Under 2.5 Goals forecasting',
      'Curated Best Picks with model agreement filtering',
      'Confidence bands with historical win rate tracking',
      'Firebase cloud-synced track record across devices',
      'Best Performing Leagues & Top Criteria insights',
      'Ad-supported with premium ad-free option',
    ],
    platform: 'iOS',
    status: 'live',
    googlePlayStatus: 'in-review',
    appStoreUrl: 'https://apps.apple.com/gb/app/goallab/id6759168029',
    appStoreTrialNote: 'First week free!',
    contentRatingUrl: '/goallab/content-rating',
    privacyUrl: '/privacy/goallab',
    termsUrl: '/terms/goallab',
  },
  {
    id: 'popgoals',
    name: 'PopGoals',
    tagline: 'League bands, bubble lake, Over / Under picks',
    description:
      'PopGoals brings the day’s football picks into a calm “bubble lake”: fixtures are grouped into bands by pooled league win-rate performance, with Over / Under 2.5 model reads, readable fixture sheets, and a phase-shifted colour world. Listen-only Firebase feed, optional ads with a simple remove-ads purchase, and motion-aware visuals you can pause.',
    color: '#9333EA',
    icon: '/images/popgoals-icon.png',
    screenshots: [],
    features: [
      'Bubble lake UI: bands float as mothers; expand for fixture “infant” bubbles',
      'League performance banding separate from per-fixture model confidence',
      'Firebase-backed daily selection + predictions; on-device presentation',
      'StoreKit subscriptions (weekly / lifetime) to remove ads; Google AdMob on free tier',
      'SwiftUI, curated warm/cool chroma phases, accessibility-friendly motion controls',
    ],
    platform: 'iOS',
    status: 'beta',
    iconHasEmbeddedBetaBadge: false,
    privacyUrl: '/privacy/popgoals',
    termsUrl: '/terms/popgoals',
    supportUrl: '/support/popgoals',
    disclaimerUrl: '/disclaimer/popgoals',
    contentRatingUrl: '/popgoals/content-rating',
  },
  {
    id: 'maincode',
    name: 'MainCode',
    tagline: 'Local events for your area',
    description:
      'Discover concerts and performing-arts events near you. MainCode fetches events from PredictHQ by postcode (e.g. Bushwick / 11237), then lets you browse by Events or Venues, save favourites, share to friends, and add items to an in-app calendar. Optional Firebase backup for when the API is unavailable.',
    color: '#E07359',
    icon: '/images/maincode-icon.png',
    screenshots: [
      '/images/maincode-1.png',
      '/images/maincode-2.png',
      '/images/maincode-3.png',
    ],
    features: [
      'Postcode-based event discovery (PredictHQ)',
      'Events and Venues tabs with search and date filters',
      'Save events and batch-share via Messages or Messenger',
      'In-app calendar planner with "Add to calendar" from events',
      'Optional Firebase backup for offline/fallback data',
      'SwiftUI, Firebase Auth & Realtime Database',
    ],
    platform: 'iOS',
    status: 'in-review',
    privacyUrl: '/privacy/maincode',
    supportUrl: '/support/maincode',
  },
  {
    id: 'contact-care',
    name: 'Contact Care',
    tagline: 'Cross-platform contact management',
    description:
      'Contact Care is a cross-platform app for managing and caring for your contacts. Placeholder — full description and features to be added.',
    color: '#14B8A6',
    icon: '/images/contact-care-icon.png',
    screenshots: [
      '/images/contact-care-1.png',
      '/images/contact-care-2.png',
      '/images/contact-care-3.png',
    ],
    features: [
      'Cross-platform (iOS & Android)',
      'Placeholder — features to be added',
    ],
    platform: 'Cross-platform',
    status: 'beta',
    privacyUrl: '/privacy/contact-care',
    supportUrl: '/support/contact-care',
  },
  {
    id: 'draw-with-friends',
    name: 'Draw With Friends',
    tagline: 'Real-time collaborative drawing',
    description: 'A fun, interactive iOS app where friends can draw together in real-time. Features include turn-based and simultaneous drawing modes, echo effects, and photo backgrounds.',
    color: '#FF6B9D',
    icon: '/images/draw-with-friends-icon.png',
    screenshots: [
      '/images/draw-with-friends-1.png',
      '/images/draw-with-friends-2.png',
      '/images/draw-with-friends-3.png',
    ],
    features: [
      'Real-time collaboration',
      'Turn-based & simultaneous modes',
      'Echo drawing effects',
      'Photo backgrounds',
      'Room-based sessions',
    ],
    appStoreUrl: 'https://apps.apple.com/gb/app/draw-with-friends/id6755112480',
    platform: 'iOS',
    status: 'live',
  },
  {
    id: 'doomscroll-stopper',
    name: 'Doomscroll Stopper',
    tagline: 'Break the scroll, reclaim your time',
    description: 'Stop endless scrolling with intelligent app blocking and mindful usage reminders. Take back control of your digital habits.',
    // Warm orange that matches the app's highlight colour better than pink
    color: '#F97316',
    icon: '/images/doomscroll-stopper-icon.png',
    screenshots: [
      '/images/doomscroll-stopper-1.png',
      '/images/doomscroll-stopper-2.png',
    ],
    features: [
      'Smart scroll detection',
      'Usage time limits',
      'Break reminders',
      'App blocking',
      'Daily insights',
    ],
    appStoreUrl: 'https://apps.apple.com/gb/app/doomscroll-stopper/id6754539688',
    platform: 'iOS',
    status: 'live',
  },
  {
    id: 'nudgetronic',
    name: 'Nudgetronic',
    tagline: 'Screen time management done right',
    description: 'Take control of your digital wellbeing with smart app blocking, grace periods, and auto-end timers.',
    color: '#4A90E2',
    icon: '/images/nudgetronic-icon.png',
    screenshots: [
      '/images/nudgetronic-1.png',
      '/images/nudgetronic-2.png',
      '/images/nudgetronic-3.png',
    ],
    features: [
      'Full-screen shields',
      '2-minute grace periods',
      'Auto-end timers',
      'Web domain blocking',
      'Category-based limits',
    ],
    appStoreUrl: 'https://apps.apple.com/gb/app/nudgetronic/id6752445547',
    platform: 'iOS',
    status: 'live',
    privacyUrl: '/privacy/nudgetronic',
    supportUrl: '/support/nudgetronic',
  },
  {
    id: 'desktop-totem',
    name: 'Desktop Totem',
    tagline: 'Your most-used apps, stacked and ready',
    description:
      'Desktop Totem keeps your most-used Mac apps in a live "totem" on your screen so you can jump back into your real work with a single click.',
    color: '#1E293B',
    icon: '/images/desktop-totem-icon.png',
    screenshots: ['/images/desktop-totem-1.png', '/images/desktop-totem-2.png'],
    features: [
      'Live ranking of your most-used apps',
      'Slim menu bar popover and optional desktop totem',
      'Always-on-top mode with one-click "hide others"',
      'Per-app quick notes ("what was I working on?")',
      'VoiceOver-friendly navigation with clear labels',
    ],
    platform: 'macOS',
    status: 'live',
    appStoreUrl: 'https://apps.apple.com/gb/app/desktop-totem/id6755545138?mt=12',
    supportUrl: '/support/desktop-totem',
    privacyUrl: '/privacy/desktop-totem',
    accessibilityUrl: '/accessibility/desktop-totem',
  },
  {
    id: 'aikido-vocabulary-app',
    name: 'Aikido Vocabulary App',
    tagline: 'Japanese Language Trainer for students of Aikido',
    description:
      'A focused Japanese vocabulary trainer for Aikido students. Learn key dojo phrases, technique names and etiquette terms with simple drills you can run between classes.',
    // Use a calm indigo/blue that matches the iOS-style screenshots better than brown
    color: '#2563EB',
    icon: '/images/aikido-vocabulary-icon.png',
    screenshots: [
      // First screenshot is used for the card; use the new main shot there
      '/images/aikido-vocab-main.png',
      '/images/aikido-vocab-1.png',
      '/images/aikido-vocab-2.png',
      '/images/aikido-vocab-3.png',
      '/images/aikido-vocab-4.png',
    ],
    features: [
      'Curated Aikido dojo vocabulary',
      'Reading + English meaning for each term',
      'Lightweight on-device progress tracking',
      'No accounts and no ads',
      'Designed for quick review between classes',
    ],
    platform: 'iOS',
    status: 'beta',
    privacyUrl: '/privacy/aikido-vocabulary',
    contentRatingUrl: '/aikido-vocabulary/content-rating',
  },
  {
    id: 'recipe-saviour',
    name: 'Recipe Saviour',
    tagline: 'Save recipes from any website',
    description: 'Extract and save recipes from any website with a single tap. Recipe Saviour automatically parses ingredients, instructions, and cooking times into a clean, readable format. Plan your weekly meals and generate smart shopping lists.',
    color: '#EF4444',
    icon: '/images/recipe-saviour-icon.png',
    screenshots: [
      '/images/recipe-saviour-2025-12-19-1.png',
      '/images/recipe-saviour-2025-12-19-2.png',
      '/images/recipe-saviour-2025-12-19-3.png',
    ],
    features: [
      'Extract recipes from any website',
      'Clean, readable format',
      'Save ingredients and instructions',
      'Smart meal planner with shared ingredients',
      'Auto-generated shopping lists',
      'Offline access to saved recipes',
    ],
    platform: 'iOS',
    status: 'live',
    appStoreUrl: 'https://apps.apple.com/gb/app/recipe-saviour/id6755662996',
    supportUrl: '/support/recipe-saviour',
    privacyUrl: '/privacy/recipe-saviour',
    disclaimerUrl: '/disclaimer/recipe-saviour',
  },
  {
    id: 'ball-finder',
    name: 'Ball Finder',
    tagline: 'Find your lost balls...',
    description: 'Use your iPhone camera to scan and find lost balls in the park. Ball Finder uses real-time detection with ML training to help you locate balls quickly, with visual guidance and haptic feedback.',
    color: '#FBBF24',
    icon: '/images/ball-finder-icon.png',
    screenshots: [
      '/images/ball-finder-1.png',
      '/images/ball-finder-2.png',
      '/images/ball-finder-3.png',
    ],
    features: [
      'Real-time camera scanning',
      'ML-powered ball detection',
      'Cumulative learning from training photos',
      'Visual bounding boxes and distance hints',
      'Haptic feedback when balls detected',
      'Diagnostic logging for troubleshooting',
    ],
    platform: 'iOS',
    status: 'beta',
  },
  {
    id: 'roma',
    name: 'Roma',
    tagline: 'All thoughts lead to Rome...',
    description: 'A delightful daily reminder app based on the premise that all men think about Rome every day. Set your reminder time, answer the daily question, and discover fun facts about Ancient Rome.',
    color: '#DC2626',
    icon: '/images/roma-icon.png',
    screenshots: [
      '/images/roma-1.png',
      '/images/roma-2.png',
      '/images/roma-3.png',
      '/images/roma-4.png',
    ],
    features: [
      'Daily reminder notifications',
      'Roman numeral time picker',
      'Visual countdown timer',
      'Fun facts about Ancient Rome',
      'Beautiful Palatino typography',
      'Thoughtful UX with 3-second delays',
    ],
    platform: 'iOS',
    status: 'beta',
  },
  {
    id: 'research-lab',
    name: 'Research Lab',
    tagline: 'Data-driven pattern recognition',
    description: 'A macOS research tool that analyzes large datasets using multi-criteria statistical models to identify high-confidence patterns. Features real-time API integration, intelligent caching for offline analysis, and exportable results for performance tracking.',
    color: '#10B981',
    icon: '/images/research-lab-icon.png',
    screenshots: [
      // No screenshots - private research tool
    ],
    features: [
      'Multi-criteria statistical analysis engine',
      'API integration with manual control',
      'Smart data caching and offline analysis',
      'Confidence scoring and filtering',
      'Searchable dataset with 1000+ daily entries',
      'Export capabilities for performance tracking',
    ],
    platform: 'macOS',
    status: 'beta',
  },
];

